"""Added leagues added column

Revision ID: 4e281b0e8067
Revises: 8ecfcb15f86c
Create Date: 2022-11-03 20:36:15.639361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e281b0e8067'
down_revision = '8ecfcb15f86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
