"""remove column and more

Revision ID: c24424d0abd2
Revises: 4e281b0e8067
Create Date: 2022-11-03 20:39:30.767685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24424d0abd2'
down_revision = '4e281b0e8067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'test_co')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('test_co', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
